dist: focal

arch:
  - amd64

os: linux

language: shell

notifications:
  email:
  - team@appwrite.io

services:
- docker

before_install:
- curl -fsSL https://get.docker.com | sh
- echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
- mkdir -p $HOME/.docker
- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
- sudo service docker start
- docker --version
- docker buildx create --use

install:
  - docker-compose up -d
  - sleep 10

script:
  - docker ps -a
  - docker-compose exec tests vendor/bin/phpunit --configuration phpunit.xml
  - docker-compose exec tests vendor/bin/psalm --show-info=true
