name: "Linter"

on: [pull_request]
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Configure Git Safe Directory
      run: git config --global --add safe.directory /app

    - run: git checkout HEAD^2

    - name: Run Linter
      run: |
        docker run --rm -v $PWD:/app composer sh -c \
        "composer install --profile --ignore-platform-reqs && composer lint"
